### ISSUE TITLE
No Issue, just info

### ISSUE THREAD

**Issue by AbsolemJackdaw** [DavidGoldman/PaintingSelectionGui#9]
Hi Davidee,  

I see you are more active here then on the minecraft forums, so I'll leave you a note here.

I have updated your mod, and am currently distributing my own updated and revamped version of the mod.  

source code here :  
https://github.com/ArtixAllMighty/PSG-Revamped  

distributed here :  
https://minecraft.curseforge.com/projects/painting-selection-gui-revamped   

if you have any objection, please contact me.
if you are okay with me continuing to update the mod, please contact me also.

~Subaraki

**Comment by DavidGoldman** [comment]
Awesome! Yep, that's fine. I'll add a link to your project in the README soon.
